# Generated by Django 4.1.8 on 2023-06-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestLeaderboard',
            fields=[
                ('leaderboard_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('serialnumber', models.IntegerField()),
            ],
            options={
                'db_table': 'latest_leaderboards',
            },
        ),
        migrations.CreateModel(
            name='MetaAverageDailyPlaytime',
            fields=[
                ('serialnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('playfabid', models.TextField()),
                ('average_playtime', models.IntegerField()),
            ],
            options={
                'db_table': 'meta_averagedailyplaytime',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playfabid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('alias_history', models.JSONField(default=dict)),
                ('badlist', models.BooleanField(default=False)),
                ('badlist_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('badlist_timestamp', models.DateTimeField(blank=True, null=True)),
                ('lastseen_serial', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Playtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'playtime',
            },
        ),
        migrations.CreateModel(
            name='GlobalXp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'globalxp',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponWarHammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponwarhammer',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponWarClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponwarclub',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponWarBow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponwarbow',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponWarAxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponwaraxe',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponTwoHandedHammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweapontwohandedhammer',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponThrowingMallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponthrowingmallet',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponThrowingKnife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponthrowingknife',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponThrowingAxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponthrowingaxe',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponSword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponsword',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponSpear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponspear',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponSledgeHammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponsledgehammer',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponShovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponshovel',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponShortSword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponshortsword',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponRapier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponrapier',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponQuarterstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponquarterstaff',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponPoleHammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponpolehammer',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponPoleAxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponpoleaxe',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponPickAxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponpickaxe',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponOneHandedSpear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweapononehandedspear',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponMorningStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponmorningstar',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponMesser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponmesser',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponMediumShield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponmediumshield',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponMaul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponmaul',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponMace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponmace',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponLightShield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponlightshield',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponLance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponlance',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponKnife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponknife',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponKatars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponkatars',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponJavelin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponjavelin',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponHighlandSword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponhighlandsword',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponHeavyShield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponheavyshield',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponHeavyMace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponheavymace',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponHeavyCrossbow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponheavycrossbow',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponHeavyCavalrySword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponheavycavalrysword',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponHatchet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponhatchet',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponHalberd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponhalberd',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponGreatsword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweapongreatsword',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponGlaive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponglaive',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponFalchion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponfalchion',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponExecutionersAxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponexecutionersaxe',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponDaneAxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweapondaneaxe',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponDagger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweapondagger',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponCudgel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponcudgel',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponCrossbow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponcrossbow',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponBow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponbow',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponBattleAxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponbattleaxe',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponBastardSword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponbastardsword',
            },
        ),
        migrations.CreateModel(
            name='ExperienceWeaponAxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceweaponaxe',
            },
        ),
        migrations.CreateModel(
            name='ExperienceVanguard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experiencevanguard',
            },
        ),
        migrations.CreateModel(
            name='ExperienceKnight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experienceknight',
            },
        ),
        migrations.CreateModel(
            name='ExperienceFootman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experiencefootman',
            },
        ),
        migrations.CreateModel(
            name='ExperienceArcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'experiencearcher',
            },
        ),
        migrations.CreateModel(
            name='DailyPlaytime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'dailyplaytime',
            },
        ),
    ]
