# Generated by Django 4.2.2 on 2023-11-25 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChivstatsSumstats',
            fields=[
                ('serial_date', models.BigIntegerField(primary_key=True, serialize=False)),
                ('unique_players', models.IntegerField()),
                ('daily_players', models.IntegerField()),
            ],
            options={
                'db_table': 'chivstats_sumstats',
            },
        ),
        migrations.CreateModel(
            name='HourlyPlayerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_hour', models.DateTimeField()),
                ('player_count', models.IntegerField()),
            ],
            options={
                'db_table': 'hourly_player_count',
                'ordering': ['timestamp_hour'],
            },
        ),
        migrations.RenameField(
            model_name='metaaveragedailyplaytime',
            old_name='average_playtime',
            new_name='stat_value',
        ),
        migrations.AlterField(
            model_name='metaaveragedailyplaytime',
            name='playfabid',
            field=models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastseen_serial',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='PlaytimeEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_value', models.IntegerField()),
                ('serialnumber', models.IntegerField()),
                ('playfabid', models.ForeignKey(db_column='playfabid', on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.player')),
            ],
            options={
                'db_table': 'playtimeex',
            },
        ),
    ]
