# Generated by Django 4.2.2 on 2024-01-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_chivstatssumstats_hourlyplayercount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(unique=True)),
                ('elo_rating', models.BigIntegerField(default=1500)),
                ('discord_username', models.CharField(blank=True, max_length=255)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('playfabid', models.CharField(blank=True, max_length=255)),
                ('discordid', models.BigIntegerField(blank=True, null=True)),
                ('matches', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ranked_players',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='cr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='gd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='peasant_cap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='peasant_cap_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
