# Generated by Django 4.2.2 on 2024-01-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_rankedplayer_player_cr_player_gd_player_peasant_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankedplayer',
            name='gamename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
