# Generated by Django 4.2.2 on 2024-01-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0004_rankedplayer_gamename'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='recent_alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
