# Generated by Django 4.2.2 on 2024-01-15 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0007_rankedplayer_elo_duelsx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankedplayer',
            name='playfabid',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='DuoTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_creation', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('elo_rating', models.BigIntegerField(default=1500)),
                ('matches_played', models.IntegerField(default=0)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('retired', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duo_team_player1', to='leaderboards.rankedplayer', to_field='playfabid')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duo_team_player2', to='leaderboards.rankedplayer', to_field='playfabid')),
            ],
            options={
                'db_table': 'duo_teams',
            },
        ),
    ]
