# Generated by Django 4.2.2 on 2024-01-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0008_alter_rankedplayer_playfabid_duoteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submitting_playfabid', models.CharField(max_length=255)),
                ('winner_playfabid', models.CharField(max_length=255)),
                ('winner_score', models.IntegerField()),
                ('winner_elo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loser_playfabid', models.CharField(max_length=255)),
                ('loser_score', models.IntegerField()),
                ('loser_elo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'duels',
                'ordering': ['-timestamp'],
            },
        ),
    ]
